
server:
  port: 9200

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    properties:
      jakarta.persistence.query.timeout: "${JAVAX_PERSISTENCE_QUERY_TIMEOUT:30000}" # General timeout for JDBC queries
      hibernate.type.wrapper_array_handling: ALLOW
      hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:h2:file:~/beaver-dev;AUTO_SERVER=TRUE}"
    username: "${SPRING_DATASOURCE_USERNAME:sa}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.h2.Driver}"

camel:
  springboot:
    routes-include-pattern: classpath:routes/*.yaml
websocket:
  enabled: true
  port: ${WEBSOCKET_PORT:9201}
  context-path: ${WEBSOCKET_CONTEXT_PATH:/websocket}
#oauth2:
#  client-id: ${OAUTH2_CLIENT_ID:iab}
#  client-secret: ${OAUTH2_CLIENT_SECRET:milesight*iab}
#  ignore-urls:
#    - "/oauth2/token"
#    - "/user/register"
#    - "/public/**"
#    - "/api/**"

logging:
  level:
    org.springframework.security: debug
    com.milesight.beaveriot: debug
