
server:
  port: 9200

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    properties:
      jakarta.persistence.query.timeout: "${JAVAX_PERSISTENCE_QUERY_TIMEOUT:30000}" # General timeout for JDBC queries
      hibernate:
        nameing:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.43.48:5432/iab}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
  liquibase:
    enabled: true
    contexts: init,dev,prod,test
    change-log: 'classpath*:db/postgres/changelog.yaml'

camel:
  springboot:
    routes-include-pattern: classpath:routes/*.yaml

logging:
  level:
    com.milesight.iab: debug

websocket:
  enabled: true
  port: ${WEBSOCKET_PORT:8081}
  context-path: ${WEBSOCKET_CONTEXT_PATH:/websocket}