
server:
  port: 9200

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    properties:
      jakarta.persistence.query.timeout: "${JAVAX_PERSISTENCE_QUERY_TIMEOUT:30000}" # General timeout for JDBC queries
      hibernate.type.wrapper_array_handling: ALLOW
      hibernate.nameing.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.45.115:5432/postgres}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
  liquibase:
    enabled: true
    contexts: init,dev,prod,test
    change-log: 'classpath*:db/postgres/changelog.yaml'

#eventbus:
#  disruptor:
#    core-pool-size: 16
#    max-pool-size: 50
#    ring-buffer-size: 4096
camel:
  springboot:
    routes-include-pattern: classpath:routes/*.yaml
websocket:
  enabled: true
  port: ${WEBSOCKET_PORT:9201}
  context-path: ${WEBSOCKET_CONTEXT_PATH:/websocket}
oauth2:
  permit-urls:
    - "/oauth2/token"
    - "/user/register"
    - "/public/**"

logging:
  level:
    org.springframework.security: debug
    com.milesight.iab: debug
